# Generated by Django 2.2 on 2020-05-06 16:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_category', models.TextField(blank=True, null=True)),
                ('site_name', models.TextField(blank=True, null=True)),
                ('input_category', models.TextField(blank=True, null=True)),
                ('output_category', models.TextField(blank=True, null=True)),
                ('output_category_ui', models.TextField(blank=True, db_column='output_category_UI', null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('item_specifications', jsonfield.fields.JSONField(blank=True, null=True)),
                ('input_category', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('site_name', models.TextField(blank=True, null=True)),
                ('image_source', models.TextField(blank=True, null=True)),
                ('txntime', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'crawled_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('items', jsonfield.fields.JSONField(blank=True, null=True)),
                ('txntime', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
