# Generated by Django 2.2 on 2020-05-21 01:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('items', jsonfield.fields.JSONField(blank=True, null=True)),
                ('txntime', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
