# Generated by Django 2.2 on 2020-05-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200521_0159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assembly',
            table='assemblies',
        ),
    ]
