# Generated by Django 2.2 on 2020-05-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200521_0215'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assembly',
            table='projects',
        ),
    ]
